version: 2.1
orbs:
  node: circleci/node@4.7.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
     executer:
        name: node/default
        tag: '10.4'
     steps:
        - checkout
        - node/with-cache:
            steps:
               - run: npm install
        - run: npm run test       
 
